### ISSUE TITLE
Write event overload not working

### ISSUE THREAD

**Issue by Dzoay** [Microsoft/dotnetsamples#31]
I have been experimenting with my own write event overload but have found that when I introduce a string as shown below I end and try and read the event in PerfView or my own TraceEvent viewer it is corrupted.

Is anything missing here?

```
[NonEvent]
public unsafe void WriteEvent(int eventId, string arg1, double arg2, int arg3)
{
    if (IsEnabled() == false)
        return;

    if (arg1 == null)
        arg1 = "";

    fixed (char* chPtr = arg1)
    {
        EventData* descrs = stackalloc EventData[3];

        descrs->DataPointer = (IntPtr)((void*)chPtr);
        descrs->Size = checked(arg1.Length + 1 * 2);
        descrs[1].DataPointer = (IntPtr)(&arg2);
        descrs[1].Size = sizeof(double);
        descrs[2].DataPointer = (IntPtr)(&arg3);
        descrs[2].Size = sizeof(int);

        WriteEventCore(eventId, 3, descrs);
    }
}
```

**Comment by khoxsey** [comment]
It looks like you have an error in your Size calculation (adding 2 to the length instead of doubling length + 1), hence the corruption. I have custom WriteEvent methods that copy strings that work fine using this idiom:
```
        descrs[0].DataPointer = ((IntPtr)chPtr);
        descrs[0].Size = ((arg1.Length + 1) * 2);
```
Note that I do actually use the extra containing set of parens, although I think they are a spurious holdover from some code I copied long ago.

**Comment by Dzoay** [comment]
Yep that was it... sigh.
Thanks for your help!
